In [30]:
import pandas as pd 
import numpy as np
from numpy import linalg as la 
from sklearn.decomposition import PCA

In [31]:
milk = pd.read_csv("milk.csv" , index_col = 0)
milk

            water  protein   fat  lactose   ash
Animal
HORSE        90.1      2.6   1.0      6.9  0.35
ORANGUTAN    88.5      1.4   3.5      6.0  0.24
MONKEY       88.4      2.2   2.7      6.4  0.18
DONKEY       90.3      1.7   1.4      6.2  0.40
HIPPO        90.4      0.6   4.5      4.4  0.10
CAMEL        87.7      3.5   3.4      4.8  0.71
BISON        86.9      4.8   1.7      5.7  0.90
BUFFALO      82.1      5.9   7.9      4.7  0.78
GUINEA PIG   81.9      7.4   7.2      2.7  0.85
CAT          81.6     10.1   6.3      4.4  0.75
FOX          81.6      6.6   5.9      4.9  0.93
LLAMA        86.5      3.9   3.2      5.6  0.80
MULE         90.0      2.0   1.8      5.5  0.47
PIG          82.8      7.1   5.1      3.7  1.10
ZEBRA        86.2      3.0   4.8      5.3  0.70
SHEEP        82.0      5.6   6.4      4.7  0.91
DOG          76.3      9.3   9.5      3.0  1.20
ELEPHANT     70.7      3.6  17.6      5.6  0.63
RABBIT       71.3     12.3  13.1      1.9  2.30
RAT          72.5      9.2  12.6      3.3  1.40
DEER         65.9     10.4  19.7      2.6  1.40
REINDEER     64.8     10.7  20.3      2.5  1.40
WHALE        64.8     11.1  21.2      1.6  1.70
SEAL         46.4      9.7  42.0      0.0  0.85
DOLPHIN      44.9     10.6  34.9      0.9  0.53

In [32]:
print("the covariance matrix is \n", milk.cov(ddof=0))

the covariance matrix is
               water    protein         fat    lactose       ash
water    157.726944 -33.967808 -127.079472  19.472912 -2.665509
protein  -33.967808  12.807456   24.249904  -5.409584  1.426962
fat     -127.079472  24.249904  106.203136 -15.556256  1.654894
lactose   19.472912  -5.409584  -15.556256   3.221376 -0.532342
ash       -2.665509   1.426962    1.654894  -0.532342  0.244654

In [33]:
sigma = milk.cov(ddof = 0)
values , vectors = la.eig(sigma)
print(values)
print(vectors)
print(vectors.shape)

[2.70880635e+02 7.80894300e+00 1.15544378e+00 2.93516575e-01
 6.50272766e-02]
[[-0.76163901  0.15607203  0.57443881 -0.25593731 -0.00798022]
 [ 0.16060436 -0.85368037  0.26796098 -0.39275281 -0.13920564]
 [ 0.62047078  0.44299977  0.5524443  -0.33676547  0.01270931]
 [-0.09474321  0.18224371 -0.53829678 -0.816355    0.04015019]
 [ 0.01232867 -0.13194613  0.05708616 -0.01987089  0.9893354 ]]
(5, 5)

In [41]:
pca_scores = np.matmul(milk,vectors)
print(pca_scores.var(ddof=0))

0    270.880635
1      7.808943
2      1.155444
3      0.293517
4      0.065027
dtype: float64

In [39]:
print(pca_scores.cov(ddof=0))

              0             1             2             3             4
0  2.708806e+02  6.445289e-14 -4.725409e-14 -3.115616e-14  1.311545e-15
1  6.445289e-14  7.808943e+00 -9.428547e-15  7.898443e-15  9.719896e-16
2 -4.725409e-14 -9.428547e-15  1.155444e+00 -5.772561e-15 -1.334037e-15
3 -3.115616e-14  7.898443e-15 -5.772561e-15  2.935166e-01  8.057664e-16
4  1.311545e-15  9.719896e-16 -1.334037e-15  8.057664e-16  6.502728e-02