In [11]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://en.wikipedia.org/wiki/Academy_Award_for_Best_Picture'

response = requests.get(url)
# print(response.text)


html_soup = BeautifulSoup(response.text,'html.parser')
type(html_soup)
html_soup

oscar_title = html_soup.find_all('tr' , style = 'background:#FAEB86')

In [2]:
name = []
year = []
dir = []

In [3]:
for i in range(len(oscar_title)):
    try:
        name.append(oscar_title[i].td.i.b.a.text)
    except:
        name.append('nan')
    try:
        ln = "https://en.wikipedia.org"+oscar_title[i].td.i.b.a['href']
        response = requests.get(ln)
        
        new_html_soup = BeautifulSoup(response.text,'html.parser')
        type(new_html_soup)
        new_html_soup
        oscar_year = new_html_soup.find_all('span' , class_ = 'bday dtstart published updated')
        year.append(oscar_year[0].text)
    except:
        year.append('nan')
    try:
        director = new_html_soup.find('td',class_ = 'infobox-data').text
        dir.append(director)
    except:
        dir.append('Nan')

In [14]:
df = pd.DataFrame({'Movie Name':name,'director':dir,'year':year})

df

                           Movie Name                     director        year
0                               Wings           William A. Wellman  1927-08-12
1                 The Broadway Melody               Harry Beaumont  1929-02-01
2      All Quiet on the Western Front              Lewis Milestone  1930-04-21
3                            Cimarron               Wesley Ruggles  1931-01-26
4                         Grand Hotel              Edmund Goulding  1932-04-12
..                                ...                          ...         ...
90                         Green Book               Peter Farrelly  2018-09-11
91                           Parasite                          기생충  2019-05-21
92                          Nomadland                   Chloé Zhao  2020-09-11
93                                nan                   Chloé Zhao         nan
94  Everything Everywhere All at Once  Daniel KwanDaniel Scheinert  2022-03-11

[95 rows x 3 columns]